# Generated by Django 4.1 on 2022-08-12 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainuser', '0012_alter_userprofile_user'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=225)),
                ('job_description', models.TextField()),
                ('category', models.ManyToManyField(related_name='jobs_category', to='jobs.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_profile_set', to='mainuser.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
