# Generated by Django 4.1 on 2022-08-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0012_alter_userprofile_user'),
        ('jobs', '0002_jobsposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsposting',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_profile', to='mainuser.userprofile'),
        ),
    ]
