# Generated by Django 4.1 on 2022-08-16 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs1', '0002_alter_blogcomment_blog_remove_blogreaction_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogreaction',
            name='user',
        ),
        migrations.AddField(
            model_name='blogreaction',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
