# Generated by Django 4.1 on 2022-08-16 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs1', '0003_remove_blogreaction_user_blogreaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogreaction',
            name='user',
        ),
        migrations.AddField(
            model_name='blogreaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
