# Generated by Django 4.1 on 2022-08-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs1', '0004_remove_blogreaction_user_blogreaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreaction',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs1.blog'),
        ),
    ]
