# Generated by Django 4.1 on 2022-08-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0002_userprofile_experience_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='end_date',
            new_name='end_date_e',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='remark',
            new_name='remark_e',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='start_date',
            new_name='start_date_e',
        ),
    ]
