# Generated by Django 4.1 on 2022-08-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0004_rename_profile_education_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='user',
            new_name='profile',
        ),
    ]
