# Generated by Django 4.1 on 2022-08-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0005_rename_user_education_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='profile',
            new_name='user',
        ),
    ]
