# Generated by Django 4.1 on 2022-08-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0012_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
